---
title: "film_notebook_ver9"
output: pdf_document
date: "2023-12-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r importing libraries}
library(tidyverse)
library(dplyr)
library(ggplot2)
```


```{r detecting which PC and importing}

if(Sys.info()['user']=='gr2757') {
  
  Project <- "/Users/gr2757/Dropbox/Film-Project/Input/AFI_data"
}

if(Sys.info()['user']=='T-800 Model 101') {
  
  Project <- "/Users/i5-760/Dropbox/Remote/Inputs"
}

if(Sys.info()['user']=='wojtek') {
   Project<-"/home/wojtek/Dropbox/Work/Film-Project/Input/AFI_data"
}

setwd(Project)

film_data_BFI = read.csv("full_set_AFI.csv")
producer_data_BFI = read.csv("full_producers_AFI.csv")
production_data_BFI = read.csv("full_production_companies_AFI.csv")
dist_company_data = read.csv("AFI_distributors_distributors.csv")

counting_producer_data = read.csv("full_producers_AFI.csv")


```


```{r importing data}
# this comes from the python script to export films
#film_data_BFI = read.csv("/Users/gr2757/Documents/Python Projects/Movies/Outputs/full_set_AFI.csv")

#this comes from python script to extract all producers from a film (multiple entries per film)
#producer_data_BFI = read.csv("/Users/gr2757/Documents/Python Projects/Movies/Outputs/full_producers_AFI.csv")


#this comes from python script to extract all producers from a film (multiple entries per film)
#production_data_BFI = read.csv("/Users/gr2757/Documents/Python Projects/Movies/Outputs/full_production_companies_AFI.csv")


```

```{r cleaning up BFI data}

#some of the files have producer, some have producer; this is to standardize it

if ("Producers" %in% colnames(film_data_BFI)) {
  # Rename the column to "producer"
  colnames(film_data_BFI)[colnames(film_data_BFI) == "Producers"] <- "Producer"
}


film_data_BFI <- subset(film_data_BFI, Producer != "")
film_data_BFI <- subset(film_data_BFI, Producer != "[None, None]")
film_data_BFI <- subset(film_data_BFI, Producer != "[None]")
film_data_BFI <- subset(film_data_BFI, Producer != "[]")


film_data_BFI <- subset(film_data_BFI, Production_Companies != "")
film_data_BFI <- subset(film_data_BFI, Production_Companies != "[None, None]")
film_data_BFI <- subset(film_data_BFI, Production_Companies != "[]")
film_data_BFI <- subset(film_data_BFI, Production_Companies != "[None]")

#At this point there is one entry per movie per producer and the production companies are in the list format

#dropping non unique entries (removing producers) to only have a dataset on films

film_data_BFI = film_data_BFI[!duplicated(film_data_BFI$Title),]

#sticking to US films
film_data_BFI <- film_data_BFI %>%
  filter(country == "United States")
#adding year subset
film_data_BFI$YEAR = as.integer(substring(film_data_BFI$Date,1,4))


#dropping exact date
film_data_BFI = select(film_data_BFI,-Date,-X, Producer, Production_Companies)

#on second thought this data is that useful since every movie with less than perfect information on producers and production companies won't be that useful. I guess this is why the relational database might be helpful to organize all this.


```

```{r cleaning up producer data}

if ("Producers" %in% colnames(producer_data_BFI)) {
  # Rename the column to "producer"
  colnames(producer_data_BFI)[colnames(producer_data_BFI) == "Producers"] <- "Producer"
}

#renaming blanks
producer_data_BFI["Producer"][producer_data_BFI["Producer"] == ""] <- "Blank Producer"



#adding year
producer_data_BFI$YEAR = substr(producer_data_BFI$Date,1,4)
#dropping production companies and date
producer_data_BFI = subset(producer_data_BFI, select = -c(Production_Companies, Date,X))
#keeping it to US data
producer_data_BFI <- producer_data_BFI %>%
  filter(country == "United States")
#at this point the data is a bunch of films with the attached producers

```

```{r cleaning up production companie data}

if ("Producers" %in% colnames(production_data_BFI)) {
  # Rename the column to "producer"
  colnames(production_data_BFI)[colnames(production_data_BFI) == "Producers"] <- "Producer"
}

#renaming blanks
production_data_BFI["Production_Companies"][production_data_BFI["Production_Companies"] == ""] <- "Blank Production"
production_data_BFI["Production_Companies"][production_data_BFI["Production_Companies"] == "[]"] <- "Blank Production"

#adding year
production_data_BFI$YEAR = substr(production_data_BFI$Date,1,4)
#dropping production companies and date
production_data_BFI = subset(production_data_BFI, select = -c(Producer, Date,X))
#keeping it to US data
production_data_BFI <- production_data_BFI %>%
  filter(country == "United States") %>%
  distinct(Title, Production_Companies, .keep_all =  TRUE)
#at this point the data is a bunch of films with the attached production companies
```

```{r production stats}
#counting how many films each production company made
production_info_BFI = production_data_BFI

#seeing how many films were produced by a company
production_counts_BFI = production_info_BFI %>%
  group_by(Production_Companies) %>%
  summarise(number_of_films = n())

#first film, last film and how long the company was active
company_life_BFI = production_info_BFI %>%
  group_by(Production_Companies) %>%
  summarise(company_life = max(as.numeric(YEAR)) - min(as.numeric(YEAR)),
            First_Apperance = min(as.numeric(YEAR)),
            Last_Apperance = max(as.numeric(YEAR)))

#count how many production companies there are per film
production_data_BFI <- production_data_BFI %>%
  group_by(Title) %>%
  mutate(ProductionCompanyCount = n_distinct(Production_Companies)) %>%
  ungroup() %>%
  mutate(BlankProduction = ifelse(Production_Companies == "Blank Production", 1, 0)) #specifying whether there was a blank producer

production_info_BFI <- production_counts_BFI %>%
  left_join(company_life_BFI, by = "Production_Companies")


#creating column for suspicion
production_info_BFI <- production_info_BFI %>%
  group_by(Production_Companies) %>%
  mutate(
    production_suspicion = case_when(
      company_life > 1  & number_of_films > 0 ~ 0, # 0 if they have made multiple movies and have a company life greater than 0
      number_of_films == 1 ~ 1,                    # 1 if they have only made 1 movie
      company_life == 1 & number_of_films > 1 ~ 2, # 2 if they have made multiple movies but all in two year
      company_life == 0 & number_of_films > 1 ~ 3, # 3 if they have made multiple movies but all in one year
    )
  ) %>%
  ungroup()
```


```{r producer stats}
#counting how many films each production company made
producer_info_BFI = producer_data_BFI

#seeing how many films were produced by a company
producer_counts_BFI = producer_info_BFI %>%
  group_by(Producer) %>%
  summarise(number_of_films = n()) 

#first film, last film and how long the company was active
career_span_BFI = producer_info_BFI %>%
  group_by(Producer) %>%
  summarise(career_span = max(as.numeric(YEAR)) - min(as.numeric(YEAR)),
            First_Apperance = min(as.numeric(YEAR)),
            Last_Apperance = max(as.numeric(YEAR)))

#counting how many films a producer made
producer_data_BFI <- producer_data_BFI %>%
  group_by(Title) %>%
  mutate(Producer_Count = n_distinct(Producer)) %>%
  ungroup() %>%
  mutate(BlankProducer = ifelse(Producer == "Blank Producer", 1, 0)) #specifying whether there was a blank producer


producer_info_BFI <- producer_counts_BFI %>%
  left_join(career_span_BFI, by = "Producer")


#creating column for suspicion
producer_info_BFI <- producer_info_BFI %>%
  group_by(Producer) %>%
  mutate(
    producer_suspicion = case_when(
      career_span > 1  & number_of_films > 0 ~ 0,  # 0 if they have made multiple movies and have a career span greater than 0
      number_of_films == 1 ~ 1,                    # 1 if they have only made 1 movie
      career_span == 1 & number_of_films > 1 ~ 2,  # 2 if they have made multiple movies but have a career length of 2 years
      career_span == 0 & number_of_films > 1 ~ 3  # 3 if they have made multiple movies but all in one year
    )
  ) %>%
  ungroup()
```


```{r merging datasets}
#subset to only have the two things need to merge
producers_info_subset = producer_info_BFI[, c("Producer", "producer_suspicion")]

#merging sus level and film data
film_suspicion_producers <- merge(producer_data_BFI, producers_info_subset, by = "Producer", all.x = TRUE)
#picking the highest values and attaching the that to the film
film_suspicion_producers = film_suspicion_producers %>%
  group_by(Title) %>%
  slice(which.max(producer_suspicion)) %>%
  ungroup() %>%
  mutate(producer_suspicion = ifelse(BlankProducer == 1, 4, producer_suspicion)) 


#subset to only have the two things need to merge
production_info_subset = production_info_BFI[, c("Production_Companies", "production_suspicion")]

#merging sus level and film data
film_suspicion_production <- merge(production_data_BFI, production_info_subset, by = "Production_Companies", all.x = TRUE)
#picking the highest values and attaching the that to the film
film_suspicion_production = film_suspicion_production %>%
  group_by(Title) %>%
  slice(which.max(production_suspicion)) %>%
  ungroup() %>% 
  mutate(production_suspicion = ifelse(BlankProduction == 1, 4, production_suspicion))


#more subset
film_suspicion_production = film_suspicion_production[, c("Title", "production_suspicion", "BlankProduction","ProductionCompanyCount")]

#left joining and adding a total
master_film_suspicion <- film_suspicion_producers %>%
  left_join(film_suspicion_production, by = "Title") %>%
  select(-Producer) %>%
  mutate(total_suspicion = producer_suspicion + production_suspicion)


```

```{r plotting sus movies over time}

ggplot(master_film_suspicion, aes(x = YEAR, fill = as.factor(production_suspicion))) +
  geom_bar(position = "fill", stat = "count") +
  scale_y_continuous(labels = scales::percent_format(scale = 100), name = "Share of Movies by Company Type") +
  labs(title = "Production Company Suspicion by Film Release (AFI)",
       x = "Year film was released",
       fill = "Level of Suspicion") +
  scale_x_discrete(
    breaks = seq(1880, 2020, by = 10),
    labels = seq(1880, 2020, by = 10)   
  )


ggplot(master_film_suspicion, aes(x = YEAR, fill = as.factor(producer_suspicion))) +
  geom_bar(position = "fill", stat = "count") +
  scale_y_continuous(labels = scales::percent_format(scale = 100), name = "Share of Movies by Producer Type") +
  labs(title = "Producer Suspicion by Film Release (AFI)",
       x = "Year film was released",
       fill = "Level of Suspicion") +
  scale_x_discrete(
    breaks = seq(1880, 2020, by = 10),
    labels = seq(1880, 2020, by = 10)   
  )
```

```{r plotting producer counts by year}

#catagoriziing producer counts

producer_credited_plot <- master_film_suspicion %>%
  filter(BlankProducer != 1) %>%
  mutate(Producer_category = cut(Producer_Count, breaks = c(0, 1, 2, 3, 4, 5, Inf), labels = c("1", "2", "3", "4", "5", "5+")))



ggplot(producer_credited_plot, aes(x = YEAR, fill = as.factor(Producer_category))) +
  geom_bar(position = "fill", stat = "count") +
  scale_y_continuous(labels = scales::percent_format(scale = 100), name = "Share of Films per Year") +
  labs(title = "Credited Producers by Film (AFI)",
       x = "Year film was released",
       fill = "Credited Producers") +
  scale_x_discrete(
    breaks = seq(1880, 2020, by = 10),
    labels = seq(1880, 2020, by = 10)   
  )
```
```{r plotting production counts by year}

#catagoriziing production counts

production_credited_plot <- master_film_suspicion %>%
  filter(BlankProduction != 1) %>%
  mutate(Production_category = cut(ProductionCompanyCount, breaks = c(0, 1, 2, 3, 4, 5, Inf), labels = c("1", "2", "3", "4", "5", "5+")))



ggplot(production_credited_plot, aes(x = YEAR, fill = as.factor(Production_category))) +
  geom_bar(position = "fill", stat = "count") +
  scale_y_continuous(labels = scales::percent_format(scale = 100), name = "Share of Films per Year") +
  labs(title = "Credited Production Companies by Film (AFI)",
       x = "Year film was released",
       fill = "Credited Production Companies") +
  scale_x_discrete(
    breaks = seq(1880, 2020, by = 10),
    labels = seq(1880, 2020, by = 10)   
  )
```
```{r working with dist companies}

#count how many blanks there are in the data
# use is.NA lol

#adding NA's to empty rows
dist_company_data["distribution"][dist_company_data["distribution"] == ""] <- NA

dist_company_data = subset(dist_company_data, select = -c(Production_Companies, Date,X, Producers, GOID))
#keeping it to US data
dist_company_data <- dist_company_data %>%
  filter(country == "United States")



dist_company_info = dist_company_data

dist_counts = dist_company_info %>%
  group_by(distribution) %>%
  summarise(films_distributed = n())



film_suspicion_producers <- merge(producer_data_BFI, producers_info_subset, by = "Producer", all.x = TRUE)

dist_company_info = merge(dist_company_info, dist_counts, by = "distribution", all.x = TRUE)

#making whether a film was distributed by a large distributor by whether it was larger than 50 or smaller
dist_company_info$major <- ifelse(dist_company_info$films_distributed 
                                  %in% dist_company_info$films_distributed[dist_company_info$films_distributed > 50], 1, 0)

#subsetting the two columns we need
major_subset = dist_company_info[, c("Title", "major")]
#dropping NAs for now
major_subset <- na.omit(major_subset)



```
 
```{r merging with master film suspition}

#merging with the whole dataset of suspition level
major_master_film_sus <- merge(master_film_suspicion, major_subset, by = "Title", all.x = TRUE)
#only keeping where major == true
major_master_film_sus <- major_master_film_sus[major_master_film_sus$major == 1, ]
#now this dataset is only films that were distributed by distribution companies that have distributed more than 50 films
```


```{r plotting only major films}
ggplot(major_master_film_sus, aes(x = YEAR, fill = as.factor(production_suspicion))) +
  geom_bar(position = "fill", stat = "count") +
  scale_y_continuous(labels = scales::percent_format(scale = 100), name = "Share of Movies by Company Type") +
  labs(title = "Production Company Suspicion by Film Release (Major films only, AFI)",
       x = "Year film was released",
       fill = "Level of Suspicion") +
  scale_x_discrete(
    breaks = seq(1880, 2020, by = 10),
    labels = seq(1880, 2020, by = 10)   
  )
```
```{r distrubtion of major films releases}
yearly_released <- major_master_film_sus %>%
  group_by(YEAR) %>%
  summarise(Count = n()) %>%
  filter(!(is.na(YEAR)))

ggplot(yearly_released, aes(x = YEAR, y = Count)) +
  geom_bar(stat = "identity")+
  labs(title = "Major Films Released by Year",
       x = "Count",
       y = "Year Released") +
  scale_x_discrete(
    breaks = seq(1880, 2020, by = 10),
    labels = seq(1880, 2020, by = 10)   
  )
```

```{r looking into spikes}
average_producers_by_year <- master_film_suspicion %>%
  group_by(YEAR) %>%
  summarize(AverageProducers = mean(Producer_Count))


ggplot(average_producers_by_year, aes(x = YEAR, y = AverageProducers)) +
  geom_line() +
  geom_point() +
  labs(x = 'Year', y = 'Average Number of Producers', title = 'Average Number of Producers by Year') +
  theme_minimal() +
  scale_x_discrete(
    breaks = seq(1880, 2020, by = 10),
    labels = seq(1880, 2020, by = 10)   
  )


films_1993 = master_film_suspicion %>%
  filter(YEAR == 1993)

films_1994 = master_film_suspicion %>%
  filter(YEAR == 1994)

print(mean(films_1993$Producer_Count))
print(mean(films_1994$Producer_Count))

#remaking producer counts plot
remake_producer_count_plot = master_film_suspicion


remake_producer_count_plot <- remake_producer_count_plot %>%
  mutate(NumProducersBin = cut(Producer_Count, breaks = c(0, 1, 2, 3, 4, 5, Inf), labels = c('1', '2', '3', '4', '5', '5+')))

remake_producer_count_plot %>%
  count(YEAR, NumProducersBin) %>%
  group_by(YEAR) %>%
  mutate(Percentage = n / sum(n) * 100) %>%
  ggplot(aes(x = as.factor(YEAR), y = Percentage, fill = as.factor(NumProducersBin))) +
  geom_bar(stat = 'identity') +
  labs(x = 'Year', y = 'Percentage of Films', title = 'Percentage of Films by Number of Producers and Year') +
  scale_y_continuous(labels = scales::percent_format()) +
  theme_minimal() +
  scale_x_discrete(
    breaks = seq(1880, 2020, by = 10),
    labels = seq(1880, 2020, by = 10)   
  )
#This graph looks fine, ill have to try re counting.



#sticking to US films
counting_producer_data <- counting_producer_data %>%
  filter(country == "United States") %>%
  filter(Producer != "")
#adding year subset
counting_producer_data$YEAR = as.integer(substring(counting_producer_data$Date,1,4))


counting_producer_data = select(counting_producer_data,-Date,-X, -country, -Production_Companies)

counting_producer_data = counting_producer_data %>%
  group_by(Title) %>%
  mutate(Producer_Count = n())

counting_producer_data <- counting_producer_data %>%
  distinct(Title, YEAR, .keep_all = TRUE)


counting_producer_data <- counting_producer_data %>%
  mutate(NumProducersBin = cut(Producer_Count, breaks = c(0, 1, 2, 3, 4, 5, Inf), labels = c('1', '2', '3', '4', '5', '5+')))

ggplot(counting_producer_data, aes(x = YEAR, fill = as.factor(NumProducersBin))) +
  geom_bar(position = "fill", stat = "count") +
  scale_y_continuous(labels = scales::percent_format(scale = 100), name = "Share of Films per Year") +
  labs(title = "Credited Producers by Film (AFI)",
       x = "Year film was released",
       fill = "Credited Producers") +
  scale_x_discrete(
    breaks = seq(1880, 2020, by = 10),
    labels = seq(1880, 2020, by = 10)   
  )

#well it's not pretty but this is a real thing of the data...


#trying without percentage
ggplot(counting_producer_data, aes(x = as.factor(YEAR), fill = NumProducersBin)) +
  geom_bar(position = "stack") +
  labs(x = 'Year', y = 'Film Count', title = 'Film Count by Number of Producers and Year') +
  theme_minimal() +
  scale_x_discrete(
    breaks = seq(1880, 2020, by = 10),
    labels = seq(1880, 2020, by = 10)   
  )
```


